learning_rate: 0.005
batch_size: 128

reshape_mode: flatten
mag_mode: orth

salt_policy: xavier
square_flag: true

calc_policy: epoch
epoch_offset: 5
epoch_interval: 5
step_interval: 0
sampling_step:
  - 100

mean: 1.0

layer_process: "normal"

weight_decay: 0.0 # 1e-05